### ISSUE TITLE
Rename to text transformer?

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#16]
## Background

I’m thinking again of the name, and would like to rename it, because when I try to say the add-on name, I think of [some other software](https://www.jetbrains.com/resharper/) for the “reshaper” part.

## Proposed solution

Could we name it “Unicodify – Text transformer”? That more accurately depicts what it does IMHO and the associations this intends [is a quite cool one](https://en.wikipedia.org/wiki/Transformers_(film)). :wink: 

## Alternatives

Not change it. I guess it’s god to change it now, as we still have not published it yet. :slightly_smiling_face:

**Comment by tdulcet** [comment]
This change is fine with me. 👍
