### ISSUE TITLE
Write Readme and AMO text

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#20]

**Comment by tdulcet** [comment]
Here is a draft list of Unicodify's features following the format of the Awesome Emoji Picker:
* Unicode autocorrection as you type:
    * Autocorrect [Unicode symbols](https://en.wikipedia.org/wiki/Miscellaneous_Symbols) (i.e. hyphens `--` with –, fractions `1/4` with ¼, etc.). Supports 87 symbols.
    * Use Unicode smart quotes ('single quotes' with ‘Unicode single quotes’ and "double quotes" with “Unicode double quotes”)
    * Convert [fractions](https://en.wikipedia.org/wiki/Number_Forms) and [mathematical constants](https://en.wikipedia.org/wiki/Mathematical_constant) to Unicode characters (i.e. `1234.25` with 1234¼, etc.). Supports all Unicode fraction characters, Pi and e constants.
    * Supports undoing autocorrections
* Context menu with selected/highlighted text:
    * [Unicode font](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols) conversion (i.e. ꜱᴍᴀʟʟ ᴄᴀᴘꜱ, 𝒮𝒸𝓇𝒾𝓅𝓉, 𝔉𝔯𝔞𝔨𝔱𝔲𝔯, etc.). Supports 22 fonts.
    * Change [casing](https://en.wikipedia.org/wiki/Letter_case#Case_styles) (i.e. UPPER CASE, lower case, tOGGLE, cASE, etc.). Supports all locales.
    * Optionally show a live preview.
    * Useful on websites that do not support changing the font or text formatting.
* Should support all websites.
* Very fast, even when typing on large documents.
* Supports the light/dark mode of your system automatically.
* Settings automatically synced between all browser instances and devices.
* Follows the [Firefox](https://design.firefox.com/photon) and [Thunderbird](https://style.thunderbird.net/) Photon Design.
* Puts your privacy first and does not send data anywhere.
* Compatible with Firefox for Android.
* Translated into several languages. [Contribute your own language!](https://github.com/rugk/unicodify/blob/main/CONTRIBUTING.md#Translations)
* Settings can be managed by your administrator.

It looks like this will be needed for both the README and AMO/ATN. Feel free to edit this and add/remove anything.

**Comment by rugk** [comment]
Yep, looks good, I'll look into adding that…
