### ISSUE TITLE
Firefox won't install unsigned (pre-)releases

### ISSUE THREAD

**Issue by dvergeylen** [rugk/unicodify#28]
Hi!

## Bug description
Firefox prevents installation of unsigned add-ons.

![Capture d’écran du 2021-04-19 09-06-19](https://user-images.githubusercontent.com/8804879/115195377-f94a7880-a0ee-11eb-84a6-7c06c33fdad5.png)

## Steps to reproduce
- Download the XPI from the pre-release
- Go to `about:addons` and select "Install from file"
- A pop up will appear saying the add-on couldn't be installed because unsigned.

### Expected behavior
- The add-on should be installable, or maybe the procedure to allow Firefox to accept unsigned versions of it should be documented somewhere to allow testing.

## System
Firefox 78.9.0esr (64 bits), Linux

Thank you for this add-on! 🍻

**Comment by rugk** [comment]
AFAIK it should now be published here: https://addons.mozilla.org/firefox/addon/unicodify-text-transformer/

**Comment by dvergeylen** [comment]
Thanks for the quick reply!

>AFAIK it should now be published here: https://addons.mozilla.org/firefox/addon/unicodify-text-transformer/

Not for me yet, but I guess it's a matter of time

![Capture d’écran du 2021-04-19 09-56-51](https://user-images.githubusercontent.com/8804879/115201471-a6c08a80-a0f5-11eb-8048-c5186d469caf.png)

**Comment by tdulcet** [comment]
> * The add-on should be installable, or maybe the procedure to allow Firefox to accept unsigned versions of it should be documented somewhere to allow testing.

You can follow [these instructions](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) to install it temporally for testing.

**Comment by rugk** [comment]
> Not for me yet, but I guess it's a matter of time

Oh yeah, it's not yet reviewed, sorry. So yes, it's a matter of time.

**Comment by dvergeylen** [comment]
> > * The add-on should be installable, or maybe the procedure to allow Firefox to accept unsigned versions of it should be documented somewhere to allow testing.
> 
> You can follow [these instructions](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) to install it temporally for testing.

Thanks for the tip! I did and I am testing it in my browser now, cool! 🎉

>>Not for me yet, but I guess it's a matter of time
>
>Oh yeah, it's not yet reviewed, sorry. So yes, it's a matter of time.

Ok, thanks, will keep it as a bookmark for now then. 🙂

Keep up the great work!
