### ISSUE TITLE
Contributing guide: add section on how to add autocorrect symbols and font styles

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#29]
We should document this, so contributors can more easily start and pick the correct file to add more stuff.

Best as a step-by-step guide.

**Comment by tdulcet** [comment]
Here is a start. You may want something more detailed then this.

Symbol autocorrections:
1. Add item to the `symbols` object in the `src/common/modules/data/Symbols.js` file.
    * Make sure the key does not conflict with any of the existing symbols. The value must be a Unicode symbol. Emoji autocorrections should instead be added to the [Awesome Emoji Picker](https://github.com/rugk/awesome-emoji-picker) if/when https://github.com/rugk/awesome-emoji-picker/pull/93/ is merged.

Unicode Font conversions:
1. Add item to the `fonts` object in the `src/common/modules/data/Fonts.js` file.
    * The value of the item needs to include either 1. all uppercase letters (A-Z) in the font, 2. all upper and lowercase letters (A-Z, a-z), 3. all uppercase letters and numbers (A-Z, 0-9), 4. all upper and lowercase letters and numbers (A-Z, a-z, 0-9) or 5. all [printable ASCII characters](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (!-~).
2. Add the name to the `menuStructure[TRANSFORMATION_TYPE.FONT]` array in the same file.
