### ISSUE TITLE
Option for nested context menu

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#44]
## Background

As explained in https://github.com/rugk/unicodify/issues/25#issuecomment-843961953:
> We could always create a nested menu, but that would of course be harder for the user to use and we would then not be able to show all the options in a single screenshot.

https://github.com/rugk/unicodify/issues/25#issuecomment-844418604:
> I’m getting lost in that many options, actually, already…

## Proposed solution

I should be able to enable a nested context menu, where the different transformations are somewhat of being grouped together…

## Alternatives

Maybe some thing of ”highlight top most used 5 ones” at the top or sort the entries by what was last used etc.
If you’d want that, please open a new issue, however. 

## Additional context

N/A

**Comment by tdulcet** [comment]
OK, I do not think your “Proposed solution” is what you meant, so maybe we could structure the nested context menu something like this:
* Superscript
* Small Caps
	* Small Caps
	* All Small Caps
	* Unicase
* Serif
	* Serif bold
	* Serif italic
	* Serif bold italic
* Sans-serif
	* Sans-serif
	* Sans-serif bold
	* Sans-serif italic
	* Sans-serif bold italic
* Script
	* Script
	* Script bold
* Fraktur
	* Fraktur
	* Fraktur bold
* Monospace
* Double-struck
* Other/Emojis
	* Circled
	* Circled (Black)
	* Squared
	* Squared (Black)
* Fullwidth
* Change casing
	* Lowercase
	* Uppercase
	* Capitalize Each Word
	* Toggle Case

I am not sure if you wanted all the items in nested menus or if you wanted more than one level of nesting. I am also not sure how this would work with the live preview option. Anyway, this will likely require a significant refactoring of the text transformation feature, similar to #17.

**Comment by rugk** [comment]
> OK, I do not think your “Proposed solution” is what you meant

Oh sorry, I had a syntax error here (cough cough caused by this add-on #14), which commented a bigger part. Corrected now.

>  am also not sure how this would work with the live preview option.

Hmm, just do not live-preview the categories should be enough, should not it? :thinking: 
Though it may look strange if some things are previewed and some are not. :thinking: 
Anyway… taht’s an implementation detail/UX thing that can be found out when implementing it and looking/comparing how it looks. I could also imagine it does sth. like not changing the top-level entries like “Superscript” to a live preview only, but still always forces to add the description, so one knows what is done there. 

But thanks for making a list of all options! It’s a good proposal that could be implemented later on…

**Comment by Thomas-D-C** [comment]
Hi :-)

I usually need only `case changing options` and nothing else.
So I don't use nested context menus, as this would only increase the time required to access them.

I sometimes need `code case changing options`, but very rarely.
So I check them in settings, then uncheck them once I'm finished, because otherwise it would create a menu that's too long with too many useless items. (But it's a bit tedious.)

IMHO, the best solution for me would be to have a nested context menu for `code case changing options`, but to keep `case changing options` at the first level.
Do you think there is a way to do that?

**Comment by tdulcet** [comment]
> Do you think there is a way to do that?

Sure, we could allow the user to set a nested context menu for each category of options. This could work good in combination with #30. Feel free to open an issue for this request.
