### ISSUE TITLE
RandomTips not working

### ISSUE THREAD

**Issue by tdulcet** [rugk/unicodify#46]
## Bug description
See https://github.com/rugk/unicodify/pull/45#issuecomment-846371820:

> one thing I noticed when taking the screenshots of the options page is that the RandomTips are still not working:
> ![image](https://user-images.githubusercontent.com/15305150/119219009-082e9d00-ba98-11eb-87db-1ce0c1b55afe.png)

Also see #23.

**Comment by rugk** [comment]
Hmm, need to debug first what's the reason for this…
