### ISSUE TITLE
Code style: Move UnicodeFontHandler to background scripts

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#6]
@tdulcet you currently included the `UnicodeFontHandler` in the `/common` dir. Is there any reason for that?

Because actually it is only used in the `background` scripts, so it should also be in that place (`/modules` dir). Only really shared modules should be in the `common` dir.

**Comment by tdulcet** [comment]
No reason, I just was unsure of the conventions. I will create a new PR to move it.
