### ISSUE TITLE
Generic search & replace for Thunderbird

### ISSUE THREAD

**Issue by marcstern** [rugk/unicodify#71]
When replying to a message, there's often some useless test I want to suppress (like some banners, anti-virus warnings, external message warning, etc.)
Would it be possible to add custom search & replace terms (regex) on the whole body?
That would be incredibly handy.
It could be triggered when opening the new message (in case of a reply).
Thnaks a lot

**Comment by tdulcet** [comment]
Thanks for the feature request. Unfortunately, I think this would be out of scope for this add-on, which focuses on just Unicode symbol autocorrections and only as the user types. It does not support either arbitrary autocorrections or blanket replace alls, which may cause unwanted changes and would prevent the user from undoing them. See #42 for more information about using the code in this add-on to implement other autocorrection extensions. 

Thunderbird specifically already has a find and replace functionality, just go to the “Edit” menu and select “Find and Replace…”. This does not support regular expressions, but that is an issue with Firefox as well. I would recommend creating a new bug for that enhancement on BMO (https://bugzilla.mozilla.org) blocking [bug 565552](https://bugzilla.mozilla.org/show_bug.cgi?id=565552). However, find and replace is probably not the right mechanism to remove arbitrary HTML from an e-mail, as it would remove the text, but likely leave the formatting/styling.

**Comment by marcstern** [comment]
Thanks.
I'd love to create this extension but I'm afraid I don't have the experience to do it :-(

**Comment by rugk** [comment]
If so, I can only agree here. Create an issue in bugzilla for that missing functionality/RegEx search feature.
As for this add-on there is unfortunately not a lot we can do here to fulfill this request and I thus close this issue.

Or as a tip: convert HTML mails to to text-only ones, then banners etc will likely also go away.
