### ISSUE TITLE
Ctrl+Z, Ctrl+Y and Ctrl+Shift+Z support in input/textarea in Firefox

### ISSUE THREAD

**Issue by rugk** [rugk/unicodify#9]
## Bug description

<kbd>Ctrl</kbd>+<kbd>Z</kbd> does not work in Firefox in some input fields ( `input` and `textarea` fields).
The same applied to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> and <kbd>Ctrl</kbd>+<kbd>Y</kbd>.

## Steps to reproduce

1. Here on GitHub a `textarea` field is used. Enter `-->` if replacement for that is enabled.
2. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo the autocorrection.

### Actual behavior

It does not undo/change the text.

### Expected behavior

Just as with <kbd>backspace</kbd> it should revert the change, too.

## System

Operating system and version: Linux/Fedora 33
Browser and version: Firefox 83
Add-on version: bb913b0

## Possible solution

In a [Content Edible field](https://developer.mozilla.org/de/docs/Web/Guide/HTML/Content_Editable) it works though.

---------

**Old feature request:**

## ~~Background~~

~~For usability reasons, I would also like to use <kbd>Ctrl</kbd>+<kbd>Z</kbd> to reverse a replacement done by this add-on.
I know currently <kbd>backspace</kbd> is possible, but <kbd>Ctrl</kbd>+<kbd>Z</kbd> is another well-known command for that.~~
~~And if you try that with normal text, all of them support <kbd>Ctrl</kbd>+<kbd>Z</kbd>.~~

~~**Attention:** If we support <kbd>Ctrl</kbd>+<kbd>Z</kbd>, we should also support <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> to re-add the text/”reverse” that decision.~~

## ~~Proposed solution~~

~~We need to listen to these keys again. I’M not sure whether this is easily possible, given that this is more of a system hotkey, but well… it’s an idea at least.~~

## ~~Alternatives~~

~~No one.~~

## ~~Additional context~~

~~AFAIK other websiites (e.g. Wikipedia’s VisualEditor) also support this, so it seems to be possible to overwrite.~~

**Comment by tdulcet** [comment]
<kbd>Ctrl</kbd>+<kbd>Z</kbd> and <kbd>Ctrl</kbd>+<kbd>Y</kbd> to undo and redo respectively should already work on `ContentEditable` elements in Firefox and everywhere in Chrome. They do not work on `input` and `textarea` fields in Firefox because of [bug 1220696](https://bugzilla.mozilla.org/show_bug.cgi?id=1220696).

**Comment by rugk** [comment]
Okay, so let’s actually that works, so I’ll change this to a bug report being blocked by that Firefox bug.
I can confirm that it works with contentediables [in here](https://developer.mozilla.org/docs/Web/Guide/HTML/Content_Editable).

**Comment by rugk** [comment]
So the question would be, could we include a workaround that may do the same as for <kbd>backspace</kbd> in `input` and `textarea` fields?

**Comment by tdulcet** [comment]
> So the question would be, could we include a workaround that may do the same as for <kbd>backspace</kbd> in `input` and `textarea` fields?

Yes, you could update this line to also accept <kbd>Ctrl</kbd>+<kbd>Z</kbd> in `input` and `textarea` fields: https://github.com/rugk/unicodify/blob/fa3fed051032c511510e262fa8de25d80780724d/src/content_scripts/autocorrect.js#L349 Although you would need to be very careful not to break the functionality in Chrome or in Firefox after that bug is fixed.

**Comment by tdulcet** [comment]
Bug 1220696 has now been fixed in Firefox 89, which is currently [scheduled for release](https://wiki.mozilla.org/Release_Management/Calendar) on May 19.
